force-app/main/default/objects/Nurse__c/Nurse__c.object-meta.xml
<CustomObject>
    <label>Nurse</label>
    <nameField>
        <displayFormat>N-{0000}</displayFormat>
        <label>Nurse_Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Nurses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rooms__c/Rooms__c.object-meta.xml
<CustomObject>
    <label>Rooms</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Room no</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rooms__c/fields/Nurse__c.field-meta.xml
<CustomField>
    <fullName>Nurse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nurse</label>
    <referenceTo>Nurse__c</referenceTo>
    <relationshipLabel>Rooms</relationshipLabel>
    <relationshipName>Rooms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/NurseRoomAllocationHelper.cls
public class NurseRoomAllocationHelper {
	    public static void checkNurseRoomLimit(List<Rooms__c> newRooms) {
        
        set<string> setofname=new set<string>();
        for(rooms__c room : newRooms){
            setofname.add(room.Nurse__c);
        }
        list<rooms__c> listofroom=[select id, Nurse__c from rooms__c where Nurse__c in: setofname];
        map<string, rooms__c> existingmapacc=new map<string, rooms__c>();
        for(rooms__c rooms1: listofroom){
            existingmapacc.put(rooms1.Nurse__c, rooms1);
            
        }
        for(rooms__c rooms2: newRooms){
            if(existingmapacc.containsKey(rooms2.Nurse__c)){
                rooms2.addError('A nurse can be allocated to only one room.');
            }
        }
    } 

}