force-app/main/default/objects/Patient__c/Patient__c.object-meta.xml
<CustomObject>
    <label>Patient</label>
    <nameField>
        <displayFormat>PAT-{0000}</displayFormat>
        <label>Patient Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient__c/fields/Bill_Paid__c.field-meta.xml
<CustomField>
    <fullName>Bill_Paid__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bill Paid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Patient__c/fields/Date_Discharged__c.field-meta.xml
<CustomField>
    <fullName>Date_Discharged__c</fullName>
    <label>Date Discharged</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Patient__c/fields/Emergency_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Emergency_Contact_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Emergency Contact Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Patient__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Patient Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ScheduledPatientEmail.cls
global class ScheduledPatientEmail implements Schedulable {
    global void execute(SchedulableContext sc) {
        // Query patients who are discharged within the next 3 days and have not paid their bill
        Date threeDaysFromNow = Date.today().addDays(3);
        List<Patient__c> patientsToEmail = [SELECT Id, Name, Bill_Paid__c, Date_Discharged__c, Emergency_Contact_Email__c 
                                            FROM Patient__c 
                                            WHERE Bill_Paid__c = false 
                                            AND Date_Discharged__c = :threeDaysFromNow];

        // Call the sendEmail method
        PatientTriggerHandler.sendEmail(patientsToEmail);
    }
}