force-app/main/default/objects/Patient__c/Patient__c.object-meta.xml
<CustomObject>
    <label>Patient</label>
    <nameField>
        <displayFormat>PAT-{0000}</displayFormat>
        <label>Patient Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Patient__c/fields/Assigned__c.field-meta.xml
<CustomField>
    <fullName>Assigned__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Doctor</label>
    <referenceTo>Doctor__c</referenceTo>
    <relationshipLabel>Patients</relationshipLabel>
    <relationshipName>Patients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Patient Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/RollUpSummaryTriggerHandler.cls
public with sharing class RollUpSummaryTriggerHandler{
    public static void afterInsert(List<Patient__c> patList){
        Set<Id> docSetId=new Set<Id>();
            for(Patient__c pat:patList)
            {
                if(pat.Assigned__c!=null)
                {
                    docSetId.add(pat.Assigned__c);
                }
            }
        RollUpSummaryHandlerService.countActivePatients(docSetId);
    }
    public static void afterUpdate(List<Patient__c> patList, Map<Id,Patient__c> oldpatMap){
        Set<Id> docSetId=new Set<Id>();
            for(Patient__c pat:patList)
            {
                if(
                pat.Active__c!=oldpatMap.get(pat.Id).Active__c ||
                (pat.Assigned__c!=null && oldpatMap.get(pat.Id).Assigned__c==null))
                
                {
                    docSetId.add(pat.Assigned__c);
                }
                else if(pat.Assigned__c!=oldpatMap.get(pat.Id).Assigned__c)
                {
                    docSetId.add(pat.Assigned__c);
                    docSetId.add(oldpatMap.get(pat.Id).Assigned__c);
                }
            }
        RollUpSummaryHandlerService.countActivePatients(docSetId);
    }
    public static void afterDelete(List<Patient__c> patList){
        Set<Id> docSetId=new Set<Id>();
            for(Patient__c pat:patList)
            {
                if(pat.Assigned__c!=null)
                {
                    docSetId.add(pat.Assigned__c);
                }
            }
        RollUpSummaryHandlerService.countActivePatients(docSetId);
    }
    public static void afterUnDelete(List<Patient__c> patList){
        Set<Id> docSetId=new Set<Id>();
            for(Patient__c pat:patList)
            {
                if(pat.Assigned__c!=null)
                {
                    docSetId.add(pat.Assigned__c);
                }
            }
        RollUpSummaryHandlerService.countActivePatients(docSetId);
    }

}