force-app/main/default/objects/Doctor__c/Doctor__c.object-meta.xml
<CustomObject>
    <description>Doctor Details</description>
    <label>Doctor</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Doctor_ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Doctor__c/fields/Active_Patients_Count__c.field-meta.xml
<CustomField>
    <fullName>Active_Patients_Count__c</fullName>
    <label>Active Patients Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Patient__c/Patient__c.object-meta.xml
<CustomObject>
    <label>Patient</label>
    <nameField>
        <displayFormat>PAT-{0000}</displayFormat>
        <label>Patient Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Patient__c/fields/Assigned__c.field-meta.xml
<CustomField>
    <fullName>Assigned__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Doctor</label>
    <referenceTo>Doctor__c</referenceTo>
    <relationshipLabel>Patients</relationshipLabel>
    <relationshipName>Patients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Patient Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/RollUpSummaryHandlerService.cls
public with sharing class RollUpSummaryHandlerService {
    public static void countActivePatients(Set<Id> docSetId){
        if(docSetId==null || docSetId.isEmpty())
        {
            return;
        }
        Map<Id, Doctor__c> activePatDocMap = new Map<Id, Doctor__c>();
        for (AggregateResult agg : [SELECT Assigned__c, COUNT(Id) FROM Patient__c WHERE Active__c=true AND Assigned__c IN :docSetId GROUP BY Assigned__c]) {
            Id docId = (Id)agg.get('Assigned__c');
            Integer totalPatients = (Integer)agg.get('expr0');
            activePatDocMap.put(docId, new Doctor__c(Id = docId, Active_Patients_Count__c = totalPatients));
        }

        for(Id docId : docSetId){
            if(!activePatDocMap.containsKey(docId)){
                activePatDocMap.put(docId, new Doctor__c(Id = docId, Active_Patients_Count__c = 0));
            }
        }
        update activePatDocMap.values();
    }
}