force-app/main/default/objects/Doctor__c/Doctor__c.object-meta.xml
<CustomObject>
    <description>Doctor Details</description>
    <label>Doctor</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Doctor_ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Doctor__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First_Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Doctor__c/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <formula>TEXT( Saluation__c ) &amp; &quot; &quot; &amp; First_Name__c  &amp;&quot; &quot;&amp; Last_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Doctor__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last_Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Patient__c/Patient__c.object-meta.xml
<CustomObject>
    <label>Patient</label>
    <nameField>
        <displayFormat>PAT-{0000}</displayFormat>
        <label>Patient Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient__c/fields/Assigned__c.field-meta.xml
<CustomField>
    <fullName>Assigned__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Doctor</label>
    <referenceTo>Doctor__c</referenceTo>
    <relationshipLabel>Patients</relationshipLabel>
    <relationshipName>Patients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient__c/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <formula>TEXT(Saluation__c) &amp;&quot; &quot;&amp; First_Name__c &amp; &quot; &quot; &amp;Last_Name__c</formula>
    <label>Full Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Patient__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Patient Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Patient__c/fields/Patient_Details__c.field-meta.xml
<CustomField>
    <fullName>Patient_Details__c</fullName>
    <formula>&quot;Date Admitted: &quot; &amp; TEXT(Date_Admitted__c) &amp; &quot; | &quot; &amp; &quot;Date Discharged: &quot; &amp; TEXT(Date_Discharged__c)</formula>
    <label>Patient Details</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Patient__c/fields/Room_No__c.field-meta.xml
<CustomField>
    <fullName>Room_No__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Room No</label>
    <referenceTo>Rooms__c</referenceTo>
    <relationshipLabel>Patients (Room No)</relationshipLabel>
    <relationshipName>Patients1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Critical</fullName>
            </value>
            <value>
                <fullName>Observation</fullName>
            </value>
            <value>
                <fullName>Recovery</fullName>
            </value>
            <value>
                <fullName>Stable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rooms__c/Rooms__c.object-meta.xml
<CustomObject>
    <label>Rooms</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Room no</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PatientController.cls
public with sharing class PatientController {
    @AuraEnabled(cacheable=true)
    public static Patient__c getPatientDetails(String name) {
        name='%'+name+'%';
        //return [Select Id,Name,Doctor__r.Name,Address__c,Email__c,ID__c,Mobile__c,Status__c,Type__c from Patient__c where Name =:name Limit 1];

        return [SELECT First_Name__c, Age__c, Address__c, Contact_Number__c ,Room_No__r.Name,Stage__c, Assigned__r.Full_Name__c FROM Patient__c WHERE First_Name__c like : name LIMIT 10];
    }
    @AuraEnabled(cacheable=true)
    public static List<Patient__c> getPatientList(){
        return [SELECT Id, First_Name__c, Last_Name__c, Address__c, Contact_Number__c, Patient_Details__c, Age__c FROM Patient__c LIMIT 10];
    }
}